add flow to CI CD

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,11 +1,33 @@
-FROM openjdk:8-jre-alpine
-
-RUN apk add --update bash && rm -rf /var/cache/apk/*
-
+FROM openjdk:8 AS TEMP_BUILD_IMAGE
 USER root
-RUN  apk update && apk upgrade && apk add netcat-openbsd
-RUN mkdir -p /usr/local/event-app
-ADD build/libs/qevent-0.0.1-SNAPSHOT.jar /usr/local/event-app/qevent-0.0.1-SNAPSHOT.jar
-ADD run.sh run.sh
+
+ENV APP_HOME=/usr/local/event-app
+WORKDIR $APP_HOME
+
+COPY build.gradle.kts settings.gradle.kts gradlew run.sh $APP_HOME/
+COPY gradle $APP_HOME/gradle
+RUN ./gradlew build || return 0
+RUN ./gradlew build || return 0
+COPY . .
+RUN ./gradlew build
+
+
+FROM openjdk:8
+USER root
+
+ENV MONGODB_URI=mongodb://event-mongodb:27017/qagile
+ENV APP_HOME=/usr/local/event-app
+ENV ARTIFACT_DIR=/build/libs
+WORKDIR $APP_HOME
+
+COPY --from=TEMP_BUILD_IMAGE $APP_HOME/$ARTIFACT_DIR .
+COPY --from=TEMP_BUILD_IMAGE $APP_HOME/src/main/resources/application-local.properties .
+COPY --from=TEMP_BUILD_IMAGE $APP_HOME/src/main/resources/db .
+COPY --from=TEMP_BUILD_IMAGE $APP_HOME/run.sh .
+
 RUN chmod +x run.sh
 CMD ./run.sh
+
+EXPOSE 8080
+
+#HEALTHCHECK CMD curl --fail http://localhost:8080/quser/ping || exit 1
